// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGxkys5rqQQKQNKMR1qspYP9eSyswWc-4',
    appId: '1:522273351311:web:d5a3751a10d1b21fb4f2fa',
    messagingSenderId: '522273351311',
    projectId: 'taskmanageapp48',
    authDomain: 'taskmanageapp48.firebaseapp.com',
    databaseURL: 'https://taskmanageapp48-default-rtdb.firebaseio.com',
    storageBucket: 'taskmanageapp48.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-VpyjtBFYSLZ9vr3b61uwW5Rj8IMz1a0',
    appId: '1:522273351311:android:b70fbfa18c37187db4f2fa',
    messagingSenderId: '522273351311',
    projectId: 'taskmanageapp48',
    databaseURL: 'https://taskmanageapp48-default-rtdb.firebaseio.com',
    storageBucket: 'taskmanageapp48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-JsJ54qIRZrvlyuBtz0thi75ilr1vYz4',
    appId: '1:522273351311:ios:0780eb3a29704f6bb4f2fa',
    messagingSenderId: '522273351311',
    projectId: 'taskmanageapp48',
    databaseURL: 'https://taskmanageapp48-default-rtdb.firebaseio.com',
    storageBucket: 'taskmanageapp48.appspot.com',
    iosClientId: '522273351311-rddkq1a0an62k3t1e8kec6ko3beqgk2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-JsJ54qIRZrvlyuBtz0thi75ilr1vYz4',
    appId: '1:522273351311:ios:0780eb3a29704f6bb4f2fa',
    messagingSenderId: '522273351311',
    projectId: 'taskmanageapp48',
    databaseURL: 'https://taskmanageapp48-default-rtdb.firebaseio.com',
    storageBucket: 'taskmanageapp48.appspot.com',
    iosClientId: '522273351311-rddkq1a0an62k3t1e8kec6ko3beqgk2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManageApp',
  );
}
